### ISSUE TITLE
Cannot npm install

### ISSUE THREAD

**Issue by VinobaGungabissoon** [niieani/aurelia-skeleton-plugin#1]
Hello, I am receiving these errors upon `npm install` 

> typings ERR! message Attempted to compile "aurelia-binding" as a global module, but it looks like an 
> external module. You'll need to remove the global option to continue.

Is this plugin skeleton still recommended?

**Comment by niieani** [comment]
Hi. It's a bit outdated now. It should work still, but the typings need to be corrected.

**Comment by niieani** [comment]
Updated slightly, but untested. Please try now.

**Comment by VinobaGungabissoon** [comment]
Ok, this time no npm install errors. I am replicating the hello-world VVM from the ES6 plugin skeleton. When I run `gulp build`, it does not construct the dist folder correctly - i.e. I don't get all module formats and the template (.html) files are missing. As a side-note, would you recommend coding aurelia plugins in TS or ES6?

**Comment by VinobaGungabissoon** [comment]
Nevermind, I had a look at both build.js files - I see what needs to be done - I'll report back if it works.

**Comment by niieani** [comment]
I always recommend TS :) But it's up to you really, what you feel comfortable with. Aurelia still has some typings missing for certain packages (e.g. for the aurelia-binding repo), so sometimes you need to duck-tape those with `any` type or live with the missing imports. 
Don't have time to fix the errors now though. 

I could recommend using a different repo as a template, one which I've created more recently and which doesn't use gulp at all: https://github.com/aurelia/validation

Just clean all the src files there and all the packages/build resources from package.json and you should be good to go!
