### ISSUE TITLE
error with gulp build

### ISSUE THREAD

**Issue by jmdavid** [niieani/aurelia-skeleton-plugin#2]
Hello,

When I build the skeleton, I get:

src\index.ts(1,50): error TS2307: Cannot find module 'aurelia-framework'.

**Comment by niieani** [comment]
Ah, this package is deprecated. Last time I run it was 2 years ago, so I'm sorry but I can't help you with it. :( Try using the aurelia CLI.

**Comment by jmdavid** [comment]
Ok, thanks.  I ended with manuel-guilbault skeleton.
BTW, what is the status of having CLI generate plugin skeleton?
(https://github.com/aurelia/cli/issues/658)
